debug: false
trace: false

logging:
  level:
    org:
      hibernate:
        SQL: error
  config: file:src/main/resources/logback-spring.xml
server:
  port: 8098
  error:
    whitelabel:
      enabled: true
    include-stacktrace: on_trace_param
spring:
  application:
    name: akilimo
  profiles:
    active: dev
  http:
    log-request-details: false
  jpa:
    properties:
      hibernate:
        generate_statistics: false
        order_inserts: true
        jdbc:
          batch_size: 500
  liquibase:
    change-log: "classpath:liquibase/master.xml"

rate:
  limit:
    enabled: false
    rate-type: minute
    max-request: 1

akilimo:
  currency:
    ngn-usd-rate: 360
    tzs-usd-rate: 2250
    kes-usd-rate: 103
plumber:
  demo-mode: false
  base-url: http://compute-prod:8000/api/
  dev-url: http://compute-dev:8001/api/
  recommendation-ng: v2/dst/recommendation/ng/compute
  recommendation-tz: v2/dst/recommendation/tz/compute
  recommendation-ng-demo: v2/dst/recommendation/demo/ng/compute
  recommendation-tz-demo: v2/dst/recommendation/demo/tz/compute


messaging:
  test-numbers:
  web-hook-url: https://enj4dfsqm8xr.x.pipedream.net
  sms:
    base-url: https://api.tsobu.co.ke
    end-point: /v1/sms/single
    sms-user:
    sms-token:
  email:
    sender:
    pass:
  firebase:
    config-file: "D:\\gdrive\\keystores\\service_accounts\\fertilizerestimate-firebase-adminsdk-htr7d-09a391143b.json"
    defaults: {topic: 'common',
               title: 'Common topic - Hello',
               message: 'Sending test message \uD83D\uDE42',
               token: 'ss22t03wz208eg:APA2idkkow223FE_0v5yHxqCLTyxAQafj6nWaqi4QzwZTW004q1PUux63UsFN',
               payloadMessageId: '123',
               payloadData: 'Hello. This is payload content.'
    }

